typography_spectrum: 0.9849661570042372
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.34096599626354873
  lightness: 0.5936141489073634
  saturation: 0.17940108431503177
  rhythmicContrast: 0.29754673945717514
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9371220648754388
analytics:
  google: null
  facebook: null
  twitter: null
name: The Cantstoppables
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Cantstoppable FB page
    url: 'https://www.facebook.com/groups/cantstoppable/'
    type: external
favicon: null
purpose: []
